#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
prompt staehle

setopt NO_FLOW_CONTROL
setopt NUMERIC_GLOB_SORT
setopt EXTENDED_GLOB

bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

# Machine-local configuration
if [ -f "${HOME}/.zshlocal" ]; then
  source "${HOME}/.zshlocal"
fi
